### ISSUE TITLE
Use Form API #states to show/hide fields and fieldsets

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/computed_field#8]
When 'Store value in the database' is unchecked, it'd be nice if the 'Database Storage Settings' fieldset was hidden...

**Comment by ghost** [comment]
Ooh, and maybe while we're at it, hide some of the other settings based on which Data Type is selected.

**Comment by ghost** [comment]
Here's a PR: https://github.com/backdrop-contrib/computed_field/pull/9

And a screencast showing the result:

![Peek 2020-11-01 21-28](https://user-images.githubusercontent.com/2385329/97800496-b81df380-1c89-11eb-8169-cc4f136216f1.gif)

**Comment by robertgarrigos** [comment]
Just created a PR as yours was missing: #10
